default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: better_books_development

test:
  <<: *default
  database: better_books_test

production:
  <<: *default
  database: better_books_production
